### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Andrey-Demidovich** [carrier-io/carrier-io#15]
Inside the docker it's unable to load werkzeug.contrib lib in install/run.py.

Is it an actual issue or I'm doing smth wrong? I'm using Ubuntu 18 with the latest Docker.

```
$docker run getcarrier/carrier-io
Traceback (most recent call last):
  File "/usr/local/bin/run", line 11, in <module>
    load_entry_point('installer==0.1.0', 'console_scripts', 'run')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2853, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2444, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/installer-0.1.0-py3.6.egg/installer/run.py", line 21, in <module>
    from werkzeug.contrib.cache import SimpleCache
ModuleNotFoundError: No module named 'werkzeug.contrib'
```

**Comment by arozumenko** [comment]
Hi @Andrey-Demidovich 

I think it is due to fact that cache was deprecated and moved to another lib
https://werkzeug.palletsprojects.com/en/0.16.x/contrib/cache/

will be fixed in next build

**Comment by arozumenko** [comment]
Fixed in 
https://github.com/carrier-io/carrier-io/commit/3d52fdc391df9dd6a2ff7555c1e6b6ecd3362bb1
