### ISSUE TITLE
Can I run this in AWS Fargate? 

### ISSUE THREAD

**Issue by asmagin** [carrier-io/carrier-io#25]
I would like to avoid the management of VMs and trying to run it in AWS Fargate with no success so far.

It is unclear from the documentation of what is happening under the hood. Are you connecting to the Docker daemon `/var/run/docker.sock` to create additional containers?

So far this is an error I'm getting:
```
Compiling Installation Configuration ... 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/docker-3.6.0-py3.6.egg/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/docker-3.6.0-py3.6.egg/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/installer-0.1.0-py3.6.egg/installer/libs/docker_part.py", line 200, in install
    self.prepare_grafana()
  File "/usr/local/lib/python3.6/site-packages/installer-0.1.0-py3.6.egg/installer/libs/docker_part.py", line 64, in prepare_grafana
    self.client.volumes.create(constants.GRAFANA_VOLUME_NAME, labels={"carrier": "grafana"})
  File "/usr/local/lib/python3.6/site-packages/docker-3.6.0-py3.6.egg/docker/models/volumes.py", line 57, in create
    obj = self.client.api.create_volume(name, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker-3.6.0-py3.6.egg/docker/api/volume.py", line 89, in create_volume
    return self._result(self._post_json(url, data=data), True)
  File "/usr/local/lib/python3.6/site-packages/docker-3.6.0-py3.6.egg/docker/api/client.py", line 274, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker-3.6.0-py3.6.egg/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/docker-3.6.0-py3.6.egg/docker/api/client.py", line 211, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/sessions.py", line 572, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

**Comment by arozumenko** [comment]
No way to avoid dealing with VM so far, maybe later, like Q4 2020
