### ISSUE TITLE
Startup of Docker on Fresh Ubuntu 18.04 VM fails

### ISSUE THREAD

**Issue by TheSecMaven** [carrier-io/carrier-io#30]
Attaching output, not able to startup this docker container on a brand new ubuntu 18.04 VM 

root@keffelercontainers2:~# docker run -it --rm -p 9999:9999 -v //var/run/docker.sock://var/run/docker.sock getcarrier/carrier-io:latest
Unable to find image 'getcarrier/carrier-io:latest' locally
latest: Pulling from getcarrier/carrier-io
aad63a933944: Pull complete 
f229563217f5: Pull complete 
bce07ec39263: Pull complete 
7fd926f0f7cc: Pull complete 
075e2aee5115: Pull complete 
deb93356e3e5: Pull complete 
1f9a58768f29: Pull complete 
e68b131e7064: Pull complete 
935ee1b81496: Pull complete 
f41de31a82b3: Pull complete 
21ad74e9f471: Pull complete 
406db970d2d6: Pull complete 
152400af2654: Pull complete 
d4017f9df6cf: Pull complete 
Digest: sha256:bba1a1b420b155a689780768ef02dbe2ca6ecde45670b47470ca05ac94dc6e1d
Status: Downloaded newer image for getcarrier/carrier-io:latest
 * Serving Flask app "installer.run" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:9999/ (Press CTRL+C to quit)
172.17.0.1 - - [21/Apr/2020 16:50:52] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [21/Apr/2020 16:50:52] "GET /static/css/carrier.css HTTP/1.1" 200 -
172.17.0.1 - - [21/Apr/2020 16:50:52] "GET /static/img/bg.png HTTP/1.1" 200 -
172.17.0.1 - - [21/Apr/2020 16:50:52] "GET /static/js/main.js HTTP/1.1" 200 -
172.17.0.1 - - [21/Apr/2020 16:50:52] "GET /static/css/style.css.map HTTP/1.1" 404 -
172.17.0.1 - - [21/Apr/2020 16:50:53] "GET /favicon.ico HTTP/1.1" 404 -
172.17.0.1 - - [21/Apr/2020 16:51:14] "POST /install HTTP/1.1" 200 -
172.17.0.1 - - [21/Apr/2020 16:51:14] "GET /response HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f72c75d3358>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3-1.24.3-py3.6.egg/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /forward-auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f72c75d3358>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Werkzeug-1.0.0-py3.6.egg/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/site-packages/Werkzeug-1.0.0-py3.6.egg/werkzeug/serving.py", line 314, in execute
    for data in application_iter:
  File "/usr/local/lib/python3.6/site-packages/Werkzeug-1.0.0-py3.6.egg/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/usr/local/lib/python3.6/site-packages/Werkzeug-1.0.0-py3.6.egg/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.6/site-packages/installer-0.1.0-py3.6.egg/installer/libs/docker_part.py", line 268, in install
    post(f"http://{self.data['dns']}/artifacts/bucket", data={"bucket": bucket})
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/sessions.py", line 659, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/sessions.py", line 659, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/sessions.py", line 238, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests-2.20.0-py3.6.egg/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /forward-auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f72c75d3358>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by TheSecMaven** [comment]
it had started all the local containers and was doing the object bucket creation step

**Comment by arozumenko** [comment]
Hi @mkkeffeler seems like you are referring to old version of installation. 
In order to install latest version please refer to https://github.com/carrier-io/carrier-io/wiki/Quick-Start
For older version with installer there are guide in https://github.com/carrier-io/carrier-io/blob/sqlite_version/README.md

Important to mention that in installer version from sqlite you’d need to follow it to the letter - e.g creation on folders, mounting it to installer container, etc.

We are planning to update docs soon, as we are moving closer to a stable release

**Comment by arozumenko** [comment]
@mkkeffeler were you able to solve the problem or need some help?

**Comment by TheSecMaven** [comment]
I see it now, I haven't done it yet as the steps look to be actively being finalized, i'll give it a few weeks and revisit :)

**Comment by arozumenko** [comment]
I'll post and update here, once we are done with the current version of installation

**Comment by arozumenko** [comment]
Hi @mkkeffeler 
this thing in worth checking https://github.com/carrier-io/installer
currently works for AWS, GCP, SSH installation, rest is in progress
