### ISSUE TITLE
Will it affect the operation of the whole carrier-io if observer-hub is not activated, such as doing some testing

### ISSUE THREAD

**Issue by majyer** [carrier-io/carrier-io#56]
I checked docker "5eb2f5bf3303 getcarrier/observer-hub:latest app" didn't up to run,It always exist

f9627b119d79        jenkins/jenkins:lts                        "/sbin/tini -- /usr/…"   2 days ago          Up 2 days               8080/tcp, 0.0.0.0:50000->50000/tcp               carrier_jenkins_1
5eb2f5bf3303        getcarrier/observer-hub:latest             "app"                    2 days ago          Exited (1) 2 days ago                                                    observer-hub
740ffab73fd5        grafana/loki:latest                        "/usr/bin/loki -conf…"   2 days ago          Up 2 days               0.0.0.0:3100->3100/tcp                           carrier-loki

I copy the logs and find no such file or directory: '/tmp/hub/config.json' ,how to fix this issue?

Traceback (most recent call last):
  File "/usr/local/bin/app", line 33, in <module>
    sys.exit(load_entry_point('observer-hub==1.0.0', 'console_scripts', 'app')())
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2872, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/observer_hub-1.0.0-py3.7.egg/observer_hub/app.py", line 25, in <module>
    config = read_config()
  File "/usr/local/lib/python3.7/site-packages/observer_hub-1.0.0-py3.7.egg/observer_hub/util.py", line 52, in read_config
    with open(CONFIG_PATH) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/hub/config.json'

**Comment by arozumenko** [comment]
not it won't affect rest of functionality, expect UI performance

**Comment by majyer** [comment]
add /tmp/hub/config.json can fix the issue

**Comment by arozumenko** [comment]
@majyer is it till actual?
